FROM oven/bun:1.3.13

WORKDIR /app

COPY package.json bun.lock ./
COPY apps/backend/package.json ./apps/backend/package.json
COPY apps/DbPollar/package.json ./apps/DbPollar/package.json
COPY apps/frontend/package.json ./apps/frontend/package.json
COPY apps/matchingEngine/package.json ./apps/matchingEngine/package.json
COPY apps/webSocketServer/package.json ./apps/webSocketServer/package.json
COPY packages ./packages

RUN bun install --frozen-lockfile

COPY . .

CMD ["bun", "apps/DbPollar/src/index.ts"]