FROM oven/bun:1.3.13

WORKDIR /app

COPY package.json bun.lock ./
COPY apps/backend/package.json ./apps/backend/package.json
COPY apps/DbPollar/package.json ./apps/DbPollar/package.json
COPY apps/frontend/package.json ./apps/frontend/package.json
COPY apps/matchingEngine/package.json ./apps/matchingEngine/package.json
COPY apps/webSocketServer/package.json ./apps/webSocketServer/package.json
COPY packages ./packages

COPY . .

RUN bun install --frozen-lockfile



EXPOSE 3000

# CMD [ "bun", "apps/backend/src/index.ts" ]
# CMD ["sh", "-c", "bunx prisma migrate deploy --config /app/packages/prismaForDB/prisma.config.ts && exec bun apps/backend/src/index.ts"]

RUN bun install --frozen-lockfile

EXPOSE 3000

CMD ["sh", "-c", "bunx prisma migrate deploy --config /app/packages/prismaForDB/prisma.config.ts && exec bun apps/backend/src/index.ts"]